# Generated by Django 4.2.7 on 2024-01-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0002_alter_droncategorymodel_weight_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droncategorymodel',
            name='weight_limit',
            field=models.IntegerField(blank=True),
        ),
    ]
