# Generated by Django 4.2.7 on 2024-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dron', '0003_alter_droncategorymodel_weight_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='state',
            field=models.IntegerField(choices=[(1, 'IDLE'), (2, 'LOADING'), (3, 'LOADED'), (4, 'DELIVERING'), (5, 'DELIVERED'), (6, 'RETURNING')], default=1),
        ),
    ]
